version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SIM_OPENAI_API_KEY=${SIM_OPENAI_API_KEY}
      - SIM_OPENAI_MODEL=${SIM_OPENAI_MODEL:-gpt-4}
      - SIM_OPENAI_MAX_OUTPUT_TOKENS=${SIM_OPENAI_MAX_OUTPUT_TOKENS:-1200}
      - SIM_OPENAI_REASONING_EFFORT=${SIM_OPENAI_REASONING_EFFORT:-minimal}
      - SIM_DATA_MODE=${SIM_DATA_MODE:-simulation}
      - SIM_SYNTHETIC_SEED=${SIM_SYNTHETIC_SEED:-4242}
    # Remove volumes for production deployment
    # volumes:
    #   - ../api:/app
    # env_file:
    #   - ../.env
  ui:
    build:
      context: ..
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8000/ws/agents}
      - NEXT_PUBLIC_DATA_MODE=${NEXT_PUBLIC_DATA_MODE:-simulation}
    # Remove volumes for production deployment
    # volumes:
    #   - ../ui:/app
    # env_file:
    #   - ../.env
    depends_on:
      - api
